FROM node:20-alpine

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm ci

# Копирование исходного кода
COPY . .

EXPOSE 8080

# Запуск в режиме разработки
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]