version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME:-ldt-med}-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ldt_med_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    container_name: ${PROJECT_NAME:-ldt-med}-pgadmin
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ${PROJECT_NAME:-ldt-med}-backend-dev
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-ldt_med_db}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TRANSCRIPTION_URL=${TRANSCRIPTION_URL}
      - ENABLE_AI_RESPONSE=${ENABLE_AI_RESPONSE:-true}
      - IS_PROXY_API_ENABLED=${IS_PROXY_API_ENABLED:-false}
      - PROXY_API_KEY=${PROXY_API_KEY}
      - IS_IMAGE_GENERATION_ENABLED=${IS_IMAGE_GENERATION_ENABLED:-true}
      # Enable polling watcher for hot-reload inside Docker on Windows/macOS
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
      - WATCHPACK_POLLING=true
      # ML Service configuration
      - ML_SERVICE_URL=http://ml-service:8000
    depends_on:
      - postgres
      - ml-service
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ${PROJECT_NAME:-ldt-med}-frontend-dev
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
      - VITE_KEYCLOAK_REALM=${VITE_KEYCLOAK_REALM}
      - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
      - VITE_KEYCLOAK_ISSUER=${VITE_KEYCLOAK_ISSUER}
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
  
  ml-service:
    build: ./ml
    container_name: ldt-med-ml
    ports:
      - "5001:8000"
    volumes:
      - ./ml:/app
    environment:
      - MODEL_PATH=/app/best_model.pth

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: 
  pgadmin-data: